### ISSUE TITLE
The demo doesn't work

### ISSUE THREAD

**Issue by vcidst** [actions-on-google-labs/nightingale-ssml-editor#1]
Demo URL, https://actions-on-google-labs.github.io/nightingale-ssml-editor/

None of the buttons have any effect and I cannot seem to figure out how to use it. Is there a video demo of this project?

**Comment by Fleker** [comment]
Ah I just loaded it and it is working as I expect. They aren't actually buttons but media elements. You drag them from the bottom onto the timeline in the middle where they become tracks. There is no video demo I know of but that could be useful.

**Comment by davidcommarmond** [comment]
@vcidst here's a quick demo on how to drag the elements onto the timeline and organize them > https://www.loom.com/share/890d72dbc81a46ec92657601c0c84cae

If you have a bit of experience with Video Editors like Adobe Premiere or Windows Movie Maker, Apple's iMovie, etc, it's more or les the same principle in terms of how to use the timeline to mix "sound samples" >> here they would be the rendered "speech elements" along with any streamed media elements.

**Comment by Fleker** [comment]
Thanks for making the demo video. Yes, the UX is modeled on various non-linear editors like Adobe Premiere (or Audition).

**Comment by vcidst** [comment]
Thank you for the responses Fleker and David! The video was super helpful, I hadn't tried drag-n-drop and was previously clicking on the individual items instead. The demo works perfectly!
